//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decryptorus.JaxWsRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.checkerfacade.cesi.com/", ConfigurationName="JaxWsRef.CheckerEndpoint")]
    public interface CheckerEndpoint {
        
        // CODEGEN: Generating message contract since element name appToken from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkDecryptRequest", ReplyAction="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkDecryptResponse")]
        Decryptorus.JaxWsRef.checkDecryptResponse checkDecrypt(Decryptorus.JaxWsRef.checkDecryptRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDecryptRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDecrypt", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Decryptorus.JaxWsRef.checkDecryptRequestBody Body;
        
        public checkDecryptRequest() {
        }
        
        public checkDecryptRequest(Decryptorus.JaxWsRef.checkDecryptRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkDecryptRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string decryptInfo;
        
        public checkDecryptRequestBody() {
        }
        
        public checkDecryptRequestBody(string appToken, string decryptInfo) {
            this.appToken = appToken;
            this.decryptInfo = decryptInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkDecryptResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkDecryptResponse", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Decryptorus.JaxWsRef.checkDecryptResponseBody Body;
        
        public checkDecryptResponse() {
        }
        
        public checkDecryptResponse(Decryptorus.JaxWsRef.checkDecryptResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkDecryptResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decryptValidation;
        
        public checkDecryptResponseBody() {
        }
        
        public checkDecryptResponseBody(string decryptValidation) {
            this.decryptValidation = decryptValidation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckerEndpointChannel : Decryptorus.JaxWsRef.CheckerEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckerEndpointClient : System.ServiceModel.ClientBase<Decryptorus.JaxWsRef.CheckerEndpoint>, Decryptorus.JaxWsRef.CheckerEndpoint {
        
        public CheckerEndpointClient() {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decryptorus.JaxWsRef.checkDecryptResponse Decryptorus.JaxWsRef.CheckerEndpoint.checkDecrypt(Decryptorus.JaxWsRef.checkDecryptRequest request) {
            return base.Channel.checkDecrypt(request);
        }
        
        public string checkDecrypt(string appToken, string decryptInfo) {
            Decryptorus.JaxWsRef.checkDecryptRequest inValue = new Decryptorus.JaxWsRef.checkDecryptRequest();
            inValue.Body = new Decryptorus.JaxWsRef.checkDecryptRequestBody();
            inValue.Body.appToken = appToken;
            inValue.Body.decryptInfo = decryptInfo;
            Decryptorus.JaxWsRef.checkDecryptResponse retVal = ((Decryptorus.JaxWsRef.CheckerEndpoint)(this)).checkDecrypt(inValue);
            return retVal.Body.decryptValidation;
        }
    }
}
