//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decryptorus.JAXWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://facade.checkerfacade.cesi.com/", ConfigurationName="JAXWS.CheckerEndpoint")]
    public interface CheckerEndpoint {
        
        // CODEGEN: Generating message contract since element name appToken from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkOperationRequest", ReplyAction="http://facade.checkerfacade.cesi.com/CheckerEndpoint/checkOperationResponse")]
        Decryptorus.JAXWS.checkOperationResponse checkOperation(Decryptorus.JAXWS.checkOperationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkOperationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkOperation", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Decryptorus.JAXWS.checkOperationRequestBody Body;
        
        public checkOperationRequest() {
        }
        
        public checkOperationRequest(Decryptorus.JAXWS.checkOperationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkOperationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string decryptInfo;
        
        public checkOperationRequestBody() {
        }
        
        public checkOperationRequestBody(string appToken, string decryptInfo) {
            this.appToken = appToken;
            this.decryptInfo = decryptInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkOperationResponse", Namespace="http://facade.checkerfacade.cesi.com/", Order=0)]
        public Decryptorus.JAXWS.checkOperationResponseBody Body;
        
        public checkOperationResponse() {
        }
        
        public checkOperationResponse(Decryptorus.JAXWS.checkOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string decryptValidation;
        
        public checkOperationResponseBody() {
        }
        
        public checkOperationResponseBody(string decryptValidation) {
            this.decryptValidation = decryptValidation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CheckerEndpointChannel : Decryptorus.JAXWS.CheckerEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckerEndpointClient : System.ServiceModel.ClientBase<Decryptorus.JAXWS.CheckerEndpoint>, Decryptorus.JAXWS.CheckerEndpoint {
        
        public CheckerEndpointClient() {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckerEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Decryptorus.JAXWS.checkOperationResponse Decryptorus.JAXWS.CheckerEndpoint.checkOperation(Decryptorus.JAXWS.checkOperationRequest request) {
            return base.Channel.checkOperation(request);
        }
        
        public string checkOperation(string appToken, string decryptInfo) {
            Decryptorus.JAXWS.checkOperationRequest inValue = new Decryptorus.JAXWS.checkOperationRequest();
            inValue.Body = new Decryptorus.JAXWS.checkOperationRequestBody();
            inValue.Body.appToken = appToken;
            inValue.Body.decryptInfo = decryptInfo;
            Decryptorus.JAXWS.checkOperationResponse retVal = ((Decryptorus.JAXWS.CheckerEndpoint)(this)).checkOperation(inValue);
            return retVal.Body.decryptValidation;
        }
    }
}
